builds:
  - main: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/checkov-docs/checkov-docs/internal/version.version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm

dockers:
- dockerfile: docker/Dockerfile
  image_templates:
  - 'ghcr.io/checkov-docs/checkov-docs:latest'
  - 'ghcr.io/checkov-docs/checkov-docs:{{ .RawVersion }}'

brews:
  - tap:
      owner: checkov-docs
      name: homebrew-tap
    commit_author:
      name: checkov-docs-bot
      email: bot@checkov-docs.io
    url_template: "https://github.com/checkov-docs/checkov-docs/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: "https://github.com/checkov-docs/"
    description: "Generate docs for `checkov` results"
    test: |
      system "#{bin}/checkov-docs version"

archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: '{{ .ProjectName }}-{{ .Tag }}_SHA256SUMS'

snapshot:
  name_template: "{{ incpatch .Version }}-devel"

# generated by: https://github.com/semantic-release/semantic-release
# changelog:

# The lines beneath this are called `modelines`. See `:help modeline`
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
