name: pr

on:
  pull_request_target:

jobs:
  size-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Apply size label
        uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/XS'
          xs_max_size: '30'
          s_label: 'size/S'
          s_max_size: '60'
          m_label: 'size/M'
          m_max_size: '150'
          l_label: 'size/L'
          l_max_size: '300'
          xl_label: 'size/XL'
          message_if_xl: ''

  first-pr-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add helpful comment to welcome new contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |-
            Welcome @${{ github.actor }}! :wave:

            It looks like this is your first PR to [checkov-docs](https://github.com/checkov-docs/checkov-docs).

            Thank you, and welcome to checkov-docs. :smiley:
