name: pr

on:
  pull_request:

jobs:
  size-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Label PR size
        uses: BedrockStreaming/pr-size-labeler@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/XS'
          xs_diff: '30'
          s_label: 'size/S'
          s_diff: '60'
          m_label: 'size/M'
          m_diff: '150'
          l_label: 'size/L'
          l_diff: '300'
          xl_label: 'size/XL'

  first-pr-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add helpful comment to welcome new contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |-
            Welcome @${{ github.actor }}! :wave:

            It looks like this is your first PR to [checkov-docs](https://github.com/checkov-docs/checkov-docs).

            Thank you, and welcome to checkov-docs. :smiley:
